[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)]
    [ValidateRange(1, 65535)]
    [int]$Port,

    [Parameter(Mandatory = $true)]
    [string]$WslIp,

    [Parameter(Mandatory = $true)]
    [string]$InfoFile,

    [switch]$DryRun,
    [switch]$Elevated
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$FirewallRuleName = 'ArkhamHorrorLocal-LAN-TCP'
$HyperVRuleName = 'ArkhamHorrorLocal-HyperV-LAN-TCP'
$WslVmCreatorId = '{40E0AC32-46A5-438A-A0B2-2B479E8F2E90}'

function Test-IPv4Address {
    param([string]$Address)

    $parsed = $null
    return [Net.IPAddress]::TryParse($Address, [ref]$parsed) -and
        $parsed.AddressFamily -eq [Net.Sockets.AddressFamily]::InterNetwork
}

function Get-WindowsIPv4Addresses {
    $addresses = @()
    try {
        $addresses = @(Get-NetIPAddress -AddressFamily IPv4 -ErrorAction Stop |
            Where-Object {
                $_.IPAddress -ne '127.0.0.1' -and
                $_.IPAddress -notlike '169.254.*'
            } |
            Select-Object -ExpandProperty IPAddress -Unique)
    }
    catch {
        $addresses = @()
    }
    return $addresses
}

function Get-WindowsLanIPv4 {
    $excludedAdapters = 'Loopback|vEthernet|WSL|Hyper-V|VirtualBox|VMware|Docker|Tailscale|ZeroTier'
    try {
        $configs = @(Get-NetIPConfiguration -ErrorAction Stop |
            Where-Object {
                $_.NetAdapter.Status -eq 'Up' -and
                $null -ne $_.IPv4DefaultGateway -and
                $_.InterfaceAlias -notmatch $excludedAdapters
            } |
            Sort-Object { $_.NetIPv4Interface.InterfaceMetric })

        foreach ($config in $configs) {
            foreach ($entry in @($config.IPv4Address)) {
                $address = [string]$entry.IPAddress
                if ((Test-IPv4Address $address) -and
                    $address -ne '127.0.0.1' -and
                    $address -notlike '169.254.*') {
                    return $address
                }
            }
        }
    }
    catch {
        # Fall through to a less selective lookup for older Windows builds.
    }

    try {
        $fallbackAddresses = @(Get-NetIPAddress -AddressFamily IPv4 -ErrorAction Stop |
            Where-Object {
                $_.InterfaceAlias -notmatch $excludedAdapters -and
                $_.IPAddress -ne '127.0.0.1' -and
                $_.IPAddress -notlike '169.254.*' -and
                $_.AddressState -eq 'Preferred'
            })
        foreach ($entry in $fallbackAddresses) {
            if (Test-IPv4Address ([string]$entry.IPAddress)) {
                return [string]$entry.IPAddress
            }
        }
    }
    catch {
        # The primary lookup above remains authoritative when this cmdlet is unavailable.
    }
    return $null
}

function Read-LanState {
    $state = @{}
    if (-not (Test-Path -LiteralPath $InfoFile -PathType Leaf)) {
        return $state
    }

    foreach ($line in @(Get-Content -LiteralPath $InfoFile -ErrorAction SilentlyContinue)) {
        if ($line -match '^([A-Z0-9_]+)=(.*)$') {
            $state[$matches[1]] = $matches[2].Trim()
        }
    }
    return $state
}

function Write-LanState {
    param(
        [int]$Ready,
        [string]$LanIp,
        [string]$Mode
    )

    $parent = Split-Path -Parent $InfoFile
    if ($parent) {
        New-Item -ItemType Directory -Path $parent -Force | Out-Null
    }
    $temporary = "$InfoFile.tmp.$PID"
    @(
        '# Generated by Configure-ArkhamHorror-LAN.ps1'
        "ARKHAM_LAN_READY=$Ready"
        "ARKHAM_LAN_IP=$LanIp"
        "ARKHAM_LAN_PORT=$Port"
        "ARKHAM_WSL_IP=$WslIp"
        "ARKHAM_LAN_MODE=$Mode"
    ) | Set-Content -LiteralPath $temporary -Encoding Ascii
    Move-Item -LiteralPath $temporary -Destination $InfoFile -Force
}

function Test-IsAdministrator {
    $identity = [Security.Principal.WindowsIdentity]::GetCurrent()
    $principal = New-Object Security.Principal.WindowsPrincipal($identity)
    return $principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
}

function Remove-PortProxy {
    param([int]$ListenPort)

    if ($ListenPort -lt 1 -or $ListenPort -gt 65535) {
        return
    }
    & "$env:SystemRoot\System32\netsh.exe" interface portproxy delete v4tov4 `
        listenaddress=0.0.0.0 listenport=$ListenPort protocol=tcp 2>$null | Out-Null
}

function Set-NatPortProxy {
    param([hashtable]$PreviousState)

    if ($PreviousState.ContainsKey('ARKHAM_LAN_PORT') -and
        $PreviousState['ARKHAM_LAN_PORT'] -match '^\d+$') {
        $oldPort = [int]$PreviousState['ARKHAM_LAN_PORT']
        if ($oldPort -ne $Port) {
            Remove-PortProxy -ListenPort $oldPort
        }
    }

    Set-Service -Name iphlpsvc -StartupType Automatic
    Start-Service -Name iphlpsvc
    Remove-PortProxy -ListenPort $Port
    & "$env:SystemRoot\System32\netsh.exe" interface portproxy add v4tov4 `
        listenaddress=0.0.0.0 listenport=$Port `
        connectaddress=$WslIp connectport=$Port protocol=tcp | Out-Null
    if ($LASTEXITCODE -ne 0) {
        throw "Unable to create the Windows $Port -> WSL $WslIp`:$Port port proxy."
    }
}

function Set-WindowsFirewallRule {
    Get-NetFirewallRule -Name $FirewallRuleName -ErrorAction SilentlyContinue |
        Remove-NetFirewallRule -ErrorAction SilentlyContinue
    New-NetFirewallRule `
        -Name $FirewallRuleName `
        -DisplayName 'Arkham Horror Local - LAN access' `
        -Description 'Allows Arkham Horror Local on this Windows PC from the local network.' `
        -Enabled True `
        -Direction Inbound `
        -Action Allow `
        -Profile Any `
        -Protocol TCP `
        -LocalPort $Port `
        -RemoteAddress LocalSubnet | Out-Null
}

function Set-HyperVFirewallRule {
    $newCommand = Get-Command New-NetFirewallHyperVRule -ErrorAction SilentlyContinue
    if ($null -eq $newCommand) {
        return
    }

    if (Get-Command Remove-NetFirewallHyperVRule -ErrorAction SilentlyContinue) {
        Get-NetFirewallHyperVRule -Name $HyperVRuleName -ErrorAction SilentlyContinue |
            Remove-NetFirewallHyperVRule -ErrorAction SilentlyContinue
    }

    $parameters = @{
        Name        = $HyperVRuleName
        DisplayName = 'Arkham Horror Local - WSL LAN access'
        Direction   = 'Inbound'
        VMCreatorId = $WslVmCreatorId
        Protocol    = 'TCP'
        LocalPorts  = @($Port)
        Action      = 'Allow'
        Enabled     = $true
    }
    if ($newCommand.Parameters.ContainsKey('RemoteAddresses')) {
        $parameters['RemoteAddresses'] = @('LocalSubnet')
    }
    New-NetFirewallHyperVRule @parameters | Out-Null
}

if (-not (Test-IPv4Address $WslIp)) {
    throw "Invalid WSL IPv4 address: $WslIp"
}

$lanIp = Get-WindowsLanIPv4
if (-not $lanIp) {
    throw 'No active Windows LAN IPv4 address with a default gateway was found.'
}

$windowsAddresses = @(Get-WindowsIPv4Addresses)
$mode = if ($windowsAddresses -contains $WslIp) { 'mirrored' } else { 'nat' }
$previous = Read-LanState

if ($DryRun) {
    Write-Output 'ARKHAM_LAN_DRY_RUN=1'
    Write-Output "ARKHAM_LAN_IP=$lanIp"
    Write-Output "ARKHAM_LAN_PORT=$Port"
    Write-Output "ARKHAM_WSL_IP=$WslIp"
    Write-Output "ARKHAM_LAN_MODE=$mode"
    exit 0
}

$stateIsCurrent = $previous.ContainsKey('ARKHAM_LAN_READY') -and
    $previous['ARKHAM_LAN_READY'] -eq '1' -and
    $previous['ARKHAM_LAN_IP'] -eq $lanIp -and
    $previous['ARKHAM_LAN_PORT'] -eq [string]$Port -and
    $previous['ARKHAM_WSL_IP'] -eq $WslIp -and
    $previous['ARKHAM_LAN_MODE'] -eq $mode

if ($stateIsCurrent -and -not $Elevated) {
    Write-Output "ARKHAM_LAN_READY=1"
    Write-Output "ARKHAM_LAN_IP=$lanIp"
    Write-Output "ARKHAM_LAN_MODE=$mode"
    exit 0
}

if (-not (Test-IsAdministrator)) {
    try {
        $powerShell = "$env:SystemRoot\System32\WindowsPowerShell\v1.0\powershell.exe"
        $arguments = "-NoProfile -ExecutionPolicy Bypass -File `"$PSCommandPath`" -Port $Port -WslIp `"$WslIp`" -InfoFile `"$InfoFile`" -Elevated"
        $process = Start-Process -FilePath $powerShell -Verb RunAs -Wait -PassThru -ArgumentList $arguments
        exit $process.ExitCode
    }
    catch {
        Write-Warning 'Administrator permission was not granted. Localhost remains available, but LAN access was not configured.'
        exit 5
    }
}

try {
    Set-WindowsFirewallRule
    if ($mode -eq 'nat') {
        Set-NatPortProxy -PreviousState $previous
    }
    else {
        # A user may have configured a NAT proxy manually before switching WSL
        # to mirrored networking. It would compete with the directly exposed
        # WSL listener on the same Windows port, so remove that exact app port.
        Remove-PortProxy -ListenPort $Port
        if ($previous.ContainsKey('ARKHAM_LAN_MODE') -and
            $previous['ARKHAM_LAN_MODE'] -eq 'nat' -and
            $previous.ContainsKey('ARKHAM_LAN_PORT') -and
            $previous['ARKHAM_LAN_PORT'] -match '^\d+$') {
            Remove-PortProxy -ListenPort ([int]$previous['ARKHAM_LAN_PORT'])
        }
        Set-HyperVFirewallRule
    }

    Write-LanState -Ready 1 -LanIp $lanIp -Mode $mode
    Write-Output 'ARKHAM_LAN_READY=1'
    Write-Output "ARKHAM_LAN_IP=$lanIp"
    Write-Output "ARKHAM_LAN_MODE=$mode"
    exit 0
}
catch {
    try {
        Write-LanState -Ready 0 -LanIp $lanIp -Mode $mode
    }
    catch {
        # Preserve the original configuration error if the status file cannot be updated.
    }
    Write-Error $_
    exit 1
}
